Consul:
  Image: "quay.io/samsung_cnct/consul"
  ImageTag: "0.6.3"
  ImagePullPolicy: "Always"
  Component: "consul"

  Replicas: 3
  Environment: "local"
  MasterToken: "token"
  GossipKey: "cg8StVXbQJ0gPvMd9o7yrg=="

  Cpu: "512m"
  Memory: "200Mi"
