apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-app
spec:
{{- if .Values.DexApp.NodePort }}
  type: NodePort
{{- end }}    
  ports:
  - name: {{.Release.Name}}-app
    protocol: TCP
    port: 80
    targetPort: 80
{{- if .Values.DexApp.NodePort }}
    nodePort: {{.Values.DexApp.NodePort}}
{{- end }}      
  selector:
    app: {{.Release.Name}}-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Release.Name}}-app
  labels:
    app: {{.Release.Name}}-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-app
    spec:
      containers:
      - name: {{.Release.Name}}-app
        image: {{.Values.DexApp.Image}}:{{.Values.DexApp.ImageTag}}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80

{{- if .Values.Dex.Tls }}
        volumeMounts:
        - name: tls
          mountPath: /etc/dex/tls
{{- end }}            

        env:
        - name: DEX_ISSUER
          value: {{.Values.Dex.Issuer}}
{{- if .Values.Dex.Tls }}
        - name: DEX_CA
          value: /etc/dex/tls/tls.ca
        - name: DEX_CERT
          value: /etc/dex/tls/tls.cert
        - name: DEX_KEY
          value: /etc/dex/tls/tls.key
{{- end }}            
        - name: DEX_APP_LISTEN_ADDRESS
          value: http://0.0.0.0:80
        - name: DEX_APP_REDIRECT_URI
          value: {{.Values.DexApp.RedirectUri}}

        resources:
          limits:
            cpu: {{ .Values.DexApp.Cpu }}
            memory: {{ .Values.DexApp.Memory }}
          requests:
            cpu: {{ .Values.DexApp.Cpu }}
            memory: {{ .Values.DexApp.Memory }}

      volumes:
{{- if .Values.Dex.Tls }}
      - name: tls
        secret:
          secretName: {{.Release.Name}}.tls
{{- end }}            
